DATALOADER:
  COCO_VERSION: dataloader_COCO_version_variable
  SIZE_DIVISIBILITY: 32
  TRANSFORM_FUNCTION: dataloader_transform_function_variable
DATASETS:
  TEST: ("coco_2017_variable_val",)
  TRAIN: ("coco_2017_variable_train",)
MODEL:
  BACKBONE:
    CONV_BODY: R-101-FPN
    FREEZE_CONV_BODY_AT: -1
    OUT_CHANNELS: 256
  MASK_ON: true
  META_ARCHITECTURE: GeneralizedRCNN
  RESNETS:
    VERSION: resnet_version_variable
  ROI_BOX_HEAD:
    FEATURE_EXTRACTOR: FPN2MLPFeatureExtractor
    POOLER_RESOLUTION: 7
    POOLER_SAMPLING_RATIO: 2
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    PREDICTOR: FPNPredictor
  ROI_HEADS:
    USE_FPN: true
  ROI_MASK_HEAD:
    FEATURE_EXTRACTOR: MaskRCNNFPNFeatureExtractor
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 2
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    PREDICTOR: MaskRCNNC4Predictor
    RESOLUTION: 28
    SHARE_BOX_FEATURE_EXTRACTOR: false
  RPN:
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    FPN_POST_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    PRE_NMS_TOP_N_TEST: 1000
    PRE_NMS_TOP_N_TRAIN: 2000
    USE_FPN: true
  SEQUENCE: variable
  SERIALIZATION_FUNCTION: serialization_function_variable
  SPECIFIC_SEQUENCE: test_loader
  WEIGHT: catalog://ImageNetPretrained/MSRA/R-101
OUTPUT_DIR: /home/projects/bagon/andreyg/Projects/Variable_Resolution/Programming/maskrcnn_combined/trained_models/variable/test_loader
SOLVER:
  BASE_LR: 0.02
  CHECKPOINT_PERIOD: 5000
  IMS_PER_BATCH: 4
  MAX_ITER: 135000
  STEPS: (80000, 120000, 130000)
  TEST_EVERY_CHECKPOINT: false
  WARMUP_FACTOR: 0.0001
  WARMUP_ITERS: 15000
  WEIGHT_DECAY: 0.0001
TENSORBOARD:
  BASE_LOG_DIR: /home/projects/bagon/andreyg/Projects/Variable_Resolution/Tensorboard_logs
  TARGET_LAYERS:
  - backbone.body.stem.conv1
