FRAME:
  new_annotation_dir_path: /home/projects/bagon/andreyg/Projects/Variable_Resolution/Datasets/annotations
  org_annotation_file_path: /home/projects/bagon/andreyg/Projects/Variable_Resolution/Datasets/annotations/gen_ann_frame_0.49_thickness/instances_val2017_org_obfiscated.json
  thickness_ratio: 0.49
LOGGING:
  logs_subdir: gen_ann_frame_0.49_thickness
  main_logger_name: main_logger_anns
  main_logs_dir: /home/projects/bagon/andreyg/Projects/Variable_Resolution/Cluster_runtime/gen_anns_with_border
