COMMAND:
  BASE_STORAGE_PATH: /home/projects/bagon/andreyg/Projects/Variable_Resolution/Cluster_runtime/model_training
  GENERATE_COMMAND: true
  NUM_GPUS: 8
  NUM_JOBS: 25
DATALOADER:
  COCO_VERSION: dataloader_COCO_version_multi_stacked
  SIZE_DIVISIBILITY: 32
  TRANSFORM_FUNCTION: dataloader_transform_function_multi_stacked_pretrained_resnet
DATASETS:
  TEST: ("coco_2017_multi_stacked_val",)
  TRAIN: ("coco_2017_multi_stacked_train",)
INPUT:
  PIXEL_MEAN: [0.477, 0.450, 0.406]
  PIXEL_STD: [1, 1, 1]
  TO_BGR255: false
MODEL:
  BACKBONE:
    CONV_BODY: R-101-FPN
    FREEZE_CONV_BODY_AT: 2
    OUT_CHANNELS: 256
  MASK_ON: true
  META_ARCHITECTURE: GeneralizedRCNN
  RESNETS:
    VERSION: resnet_version_multi_stacked
  ROI_BOX_HEAD:
    FEATURE_EXTRACTOR: FPN2MLPFeatureExtractor
    POOLER_RESOLUTION: 7
    POOLER_SAMPLING_RATIO: 2
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    PREDICTOR: FPNPredictor
  ROI_HEADS:
    USE_FPN: true
  ROI_MASK_HEAD:
    FEATURE_EXTRACTOR: MaskRCNNFPNFeatureExtractor
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 2
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    PREDICTOR: MaskRCNNC4Predictor
    RESOLUTION: 28
    SHARE_BOX_FEATURE_EXTRACTOR: false
  RPN:
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    FPN_POST_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    PRE_NMS_TOP_N_TEST: 1000
    PRE_NMS_TOP_N_TRAIN: 2000
    USE_FPN: true
  SEQUENCE: multi_stacked_pretrained_resnet
  SERIALIZATION_FUNCTION: serialization_function_multi_stacked
  SERIALIZATION_SEQUENCE_CUSTOM:
    - ['"backbone.body.stem.conv1.weight"', "[:, 0:3, :, :]", '"conv1.weight"', "[:]", "/home/projects/bagon/andreyg/Projects/Variable_Resolution/Programming/maskrcnn_combined/pretrained_models/resnet_multi_stacked_single_custom_norm/checkpoint_090.pth.tar"]
    - ['"backbone.body.stem.conv1.weight"', "[:, 6:9, :, :]", '"backbone.body.stem.conv1.weight"', "[:]", "/home/projects/bagon/andreyg/Projects/Variable_Resolution/Programming/maskrcnn_combined/trained_models/equiconst/from_combined_90k_0.02_lr/last_checkpoint/model_0090000.pth"]
    - ['"backbone.body.stem.bn1.weight"', "[:]", '"bn1.weight"', "[:]", "catalog://ImageNetPretrained/MSRA/R-101"]
  SPECIFIC_SEQUENCE: baseline
  WEIGHT: /home/projects/bagon/andreyg/Projects/Variable_Resolution/Programming/maskrcnn_combined/pretrained_models/resnet_baseline/checkpoint_090.pth.tar
OUTPUT_DIR: /home/projects/bagon/andreyg/Projects/Variable_Resolution/Programming/maskrcnn_combined/trained_models/multi_stacked_pretrained_resnet/baseline
SOLVER:
  BASE_LR: 0.02
  CHECKPOINT_PERIOD: 5000
  IMS_PER_BATCH: 16
  MAX_ITER: 90000
  STEPS: (60000, 80000)
  TEST_EVERY_CHECKPOINT: false
  WARMUP_FACTOR: 0.333333333
  WARMUP_ITERS: 500
  WEIGHT_DECAY: 0.0001
TENSORBOARD:
  BASE_LOG_DIR: /home/projects/bagon/andreyg/Projects/Variable_Resolution/Tensorboard_logs
  TARGET_LAYERS:
  - backbone.body.stem.conv1
