COMMAND:
  BASE_STORAGE_PATH: /home/projects/bagon/andreyg/Projects/Variable_Resolution/Cluster_runtime/model_training
  GENERATE_COMMAND: True
  NUM_GPUS: 8
  NUM_JOBS: 25
DATALOADER:
  COCO_VERSION: dataloader_COCO_version_multi_stacked
  TRANSFORM_FUNCTION: dataloader_transform_function_multi_stacked_pretrained_resnet
  SIZE_DIVISIBILITY: 32
DATASETS:
  TEST: ("coco_2017_multi_ch_val",)
  TRAIN: ("coco_2017_multi_ch_train",)
MODEL:
  SEQUENCE: "multi_stacked_pretrained_resnet"
  SPECIFIC_SEQUENCE: "Nothing"
  BACKBONE:
    CONV_BODY: R-101-FPN
    FREEZE_CONV_BODY_AT: 2
    OUT_CHANNELS: 256
  RESNETS:
    VERSION: "resnet_version_multi_stacked"
  MASK_ON: true
  META_ARCHITECTURE: GeneralizedRCNN
  ROI_BOX_HEAD:
    FEATURE_EXTRACTOR: FPN2MLPFeatureExtractor
    POOLER_RESOLUTION: 7
    POOLER_SAMPLING_RATIO: 2
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    PREDICTOR: FPNPredictor
  ROI_HEADS:
    USE_FPN: true
  ROI_MASK_HEAD:
    FEATURE_EXTRACTOR: MaskRCNNFPNFeatureExtractor
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 2
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    PREDICTOR: MaskRCNNC4Predictor
    RESOLUTION: 28
    SHARE_BOX_FEATURE_EXTRACTOR: false
  RPN:
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    FPN_POST_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    PRE_NMS_TOP_N_TEST: 1000
    PRE_NMS_TOP_N_TRAIN: 2000
    USE_FPN: true
  WEIGHT: /home/projects/bagon/andreyg/Projects/Variable_Resolution/Programming/maskrcnn_combined/pretrained_models/resnet_multi_stacked_single_custom_norm/checkpoint_090.pth.tar
  SERIALIZATION_FUNCTION: "serialization_function_multi_stacked"
SOLVER:
  CHECKPOINT_PERIOD: 5000
  BASE_LR: 0.02
  IMS_PER_BATCH: 16
  TEST_EVERY_CHECKPOINT: False
  MAX_ITER: 90000
  STEPS: (60000, 80000)
  WARMUP_FACTOR: 0.333333333
  WARMUP_ITERS: 500
  WEIGHT_DECAY: 0.0001
OUTPUT_DIR: ""
TENSORBOARD:
  BASE_LOG_DIR: /home/projects/bagon/andreyg/Projects/Variable_Resolution/Tensorboard_logs
  TARGET_LAYERS: ["backbone.body.stem.conv1"]
